FROM rover-image

ARG ROS_DISTRO=humble

#python3-catkin-tools python3-pip 
RUN apt-get update && apt-get install -y ros-${ROS_DISTRO}-rtabmap-ros ros-${ROS_DISTRO}-rtabmap ros-${ROS_DISTRO}-grid-map 
# Install ntpdate to sync time
RUN apt-get install -y ntpdate
# Install image processing packages
RUN apt-get install -y ros-${ROS_DISTRO}-stereo-image-proc ros-${ROS_DISTRO}-image-proc ros-${ROS_DISTRO}-image-transport-plugins && rm -rf /var/lib/apt/lists/*

# Install any additional dependencies from requirements.txt
COPY requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

# Synchronize time
RUN ntpdate -q pool.ntp.org

RUN echo "alias camera='ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zed2i'" >> /root/.bashrc
